### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by neupanedipen** [larsdroid/Player#3]
Have you compiled this as an apk or submitted to playstore or fdroid? I would love to use this app but don't have any expertise to compile this as an app. So it would be great if you could put an apk file.
Thank you!

**Comment by larsdroid** [comment]
Thanks for your interest! I'll soon be putting this up on the play store, but there are still a few bugs and oddities that need to be fixed first.

**Comment by neupanedipen** [comment]
That would be great. Thank you! Waiting for the release.
